editedEncounterKeywords = {
    ("Eye of the Storm", "Painted World of Ariamis"): ["hidden","timer"],
    ("Frozen Revolutions", "Painted World of Ariamis"): ["trial"],
    ("Inhospitable Ground", "Painted World of Ariamis"): ["snowstorm", "bitterCold"],
    ('No Safe Haven', 'Painted World of Ariamis'): ["poisonMist", "snowstorm", "bitterCold"],
    ("Promised Respite", "Painted World of Ariamis"): ["snowstorm", "bitterCold"],
    ("The First Bastion", "Painted World of Ariamis"): ["trial","timer","timer","timer"],
    ("Velka's Chosen", "Painted World of Ariamis"): ["barrage"],
    ("Depths of the Cathedral", "The Sunless City"): ["mimic"],
    ("Flooded Fortress", "The Sunless City"): ["trial", "gang", "difficultTerrain", "permanentTraps"],
    ("Illusionary Doorway", "The Sunless City"): ["illusion","timer"],
    ("Parish Church", "The Sunless City"): ["mimic", "illusion", "trial","timer","timer"],
    ("Kingdom's Messengers", "The Sunless City"): ["trial"],
    ("The Grand Hall", "The Sunless City"): ["trial","mimic"],
    ("Twilight Falls", "The Sunless City"): ["illusion"],
    ("Dark Resurrection", "Tomb of Giants"): ["darkness"],
    ("Death's Precipice", "Tomb of Giants"): ["barrage","blockedExits", "cramped"],
    ("Far From the Sun", "Tomb of Giants"): ["darkness"],
    ("Giant's Coffin", "Tomb of Giants"): ["onslaught","trial","timer"],
    ("In Deep Water", "Tomb of Giants"): ["timer"],
    ("Lakeview Refuge", "Tomb of Giants"): ["onslaught","darkness","trial"],
    ("Last Rites", "Tomb of Giants"): ["timer"],
    ("Last Shred of Light", "Tomb of Giants"): ["darkness"],
    ("Pitch Black", "Tomb of Giants"): ["darkness"],
    ("Skeleton Overlord", "Tomb of Giants"): ["timer"],
    ("The Beast From the Depths", "Tomb of Giants"): ["trial"],
    ("The Locked Grave", "Tomb of Giants"): ["trial"],
    ("The Mass Grave", "Tomb of Giants"): ["onslaught","timer","timer","timer"]
}
