enemyNames = {
    1: "Alonne Bow Knight",
    2: "Alonne Knight Captain",
    3: "Alonne Sword Knight",
    4: "Black Hollow Mage",
    5: "Bonewheel Skeleton",
    6: "Crossbow Hollow",
    7: "Crow Demon",
    8: "Demonic Foliage",
    9: "Engorged Zombie",
    10: "Falchion Skeleton",
    11: "Firebomb Hollow",
    12: "Giant Skeleton Archer",
    13: "Giant Skeleton Soldier",
    14: "Hollow Soldier",
    15: "Ironclad Soldier",
    16: "Large Hollow Soldier",
    17: "Mushroom Child",
    18: "Mushroom Parent",
    19: "Necromancer",
    20: "Phalanx",
    21: "Phalanx Hollow",
    22: "Plow Scarecrow",
    23: "Sentinel",
    24: "Shears Scarecrow",
    25: "Silver Knight Greatbowman",
    26: "Silver Knight Spearman",
    27: "Silver Knight Swordsman",
    28: "Skeleton Archer",
    29: "Skeleton Beast",
    30: "Skeleton Soldier",
    31: "Snow Rat",
    32: "Stone Guardian",
    33: "Stone Knight",
    34: "Mimic",
    35: "Armorer Dennis",
    36: "Fencer Sharron",
    37: "Invader Brylex",
    38: "Kirk Knight of Thorns",
    39: "Longfinger Kirk",
    40: "Maldron the Assassin",
    41: "Maneater Mildred",
    42: "Marvelous Chester",
    43: "Melinda the Butcher",
    44: "Oliver the Collector",
    45: "Paladin Leeroy",
    46: "Xanthous King Jeremiah",
    47: "Hungry Mimic",
    48: "Voracious Mimic"
}
