# ui/event_mode/event_card_text.py
EVENT_CARD_TEXT: dict[str, str] = {
    "Alluring Skull": "+1 dodge.",
    "Big Pilgrim's Key": "Add a shortcut.",
    "Blacksmith's Trial": "Reroll an attack/defence roll, gain an upgrade treasure if you don't.",
    "Bleak Bonfire Ascetic": "Enemies get +1 dodge difficulty.",
    "Bloodstained Bonfire Ascetic": "Enemy attacks gain Bleed.",
    "Cracked Bonfire Ascetic": "Enemy attacks gain Stagger.",
    "Firekeeper's Boon": "Upgrade a stat for free.",
    "Fleeting Glory": "Double or nothing souls. Full heal instead of dying.",
    "Forgotten Supplies": "Refresh all tokens.",
    "Frozen Bonfire Ascetic": "Enemy attacks gain Frostbite.",
    "Green Blossom": "Move without spending stamina.",
    "Hearty Bonfire Ascetic": "Enemies get +1 health.",
    "Lifegem": "Heal 1 at the start of each turn.",
    "Lost Envoy": "One character isn't placed until a certain Timer value.",
    "Lost to Time": "Potentially lose an item from the inventory.",
    "Martial Bonfire Ascetic": "Enemy attacks get +1 damage.",
    "Obscured Knowledge": "Equip an item, ignoring stats.",
    "Pine Resin": "+1 damage.",
    "Princess Guard": "Ignore a fatal attack, gain an Ember if you don't.",
    "Rare Vagrant": "Draw 2 treasure.",
    "Repair Powder": "-1 damage from enemy attacks.",
    "Rite of Rekindling": "Undo stat upgrades.",
    "Scout Ahead": "Get another encounter option.",
    "Scrying Stone": "You may discard any of the next 3 event cards.",
    "Skeletal Reforging": "Discard up to 3 items for 1 soul each.",
    "Stolen Artifact": "Draw 5 treasure, keep 1.",
    "Trustworthy Promise": "Double or nothing souls.",
    "Undead Merchant": "Purchase treasure.",
    "Unhallowed Offering": "Consume tokens for 1 soul each.",
    "Virulent Bonfire Ascetic": "Enemy attacks gain Poison.",
}
